
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.ComboBoxEntry propertyInput;
	
	private global::Gtk.Button searchButton;
	
	private global::Gtk.Label searchReportLabel;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.RadioButton addRadioButton;
	
	private global::Gtk.RadioButton multiplyRadioButton;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.SpinButton numInput;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.CheckButton integerModeCheck;
	
	private global::Gtk.VSeparator vseparator3;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.CheckButton delimiterCheckBox;
	
	private global::Gtk.Entry delimiterEntry;
	
	private global::Gtk.Label GtkLabel6;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView logWindow;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VSeparator vseparator2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.TreeView fileList;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("BatchPropertyEditor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(12));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Property Name </b>");
		this.label5.UseMarkup = true;
		this.hbox8.Add (this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox1.Add (this.hbox8);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.propertyInput = global::Gtk.ComboBoxEntry.NewText ();
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cost"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("ammo_mag_size"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("inv_weight"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("fire_dispersion_base"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("control_inertion_factor"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_relax_speed"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_relax_speed_ai"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_dispersion"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_step_angle_horz"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_dispersion_inc"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_dispertion_frac"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_max_angle"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("cam_max_angle_horz"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("fire_dispersion_condition_factor"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("misfire_probability"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("misfire_condition_k"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("condition_shot_dec"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("PDM_disp_base"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("PDM_disp_vel_factor"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("PDM_disp_accel_factor"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("PDM_crouch"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("PDM_crouch_no_acc"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("hit_power"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("hit_impulse"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("fire_distance"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("bullet_speed"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("rpm"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("time_to_aim"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("silencer_hit_power"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("silencer_hit_impulse"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("silencer_fire_distance"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("silencer_bullet_speed"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("light_var_color"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("light_var_range"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("light_time"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("ph_mass"));
		this.propertyInput.AppendText (global::Mono.Unix.Catalog.GetString ("scope_zoom_factor"));
		this.propertyInput.Name = "propertyInput";
		this.hbox1.Add (this.propertyInput);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.propertyInput]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.searchButton = new global::Gtk.Button ();
		this.searchButton.CanFocus = true;
		this.searchButton.Name = "searchButton";
		this.searchButton.UseUnderline = true;
		this.searchButton.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.hbox1.Add (this.searchButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.searchButton]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.searchReportLabel = new global::Gtk.Label ();
		this.searchReportLabel.Name = "searchReportLabel";
		this.searchReportLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Found 0 instances.");
		this.vbox1.Add (this.searchReportLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.searchReportLabel]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.addRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Add/Subtract"));
		this.addRadioButton.CanFocus = true;
		this.addRadioButton.Name = "addRadioButton";
		this.addRadioButton.DrawIndicator = true;
		this.addRadioButton.UseUnderline = true;
		this.addRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox3.Add (this.addRadioButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.addRadioButton]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.multiplyRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Multiply"));
		this.multiplyRadioButton.CanFocus = true;
		this.multiplyRadioButton.Name = "multiplyRadioButton";
		this.multiplyRadioButton.DrawIndicator = true;
		this.multiplyRadioButton.UseUnderline = true;
		this.multiplyRadioButton.Group = this.addRadioButton.Group;
		this.vbox3.Add (this.multiplyRadioButton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.multiplyRadioButton]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w10.Position = 0;
		w10.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("by");
		this.hbox3.Add (this.label2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		w11.Padding = ((uint)(9));
		// Container child hbox3.Gtk.Box+BoxChild
		this.numInput = new global::Gtk.SpinButton (-100D, 100D, 0.1D);
		this.numInput.CanFocus = true;
		this.numInput.Name = "numInput";
		this.numInput.Adjustment.PageIncrement = 10D;
		this.numInput.ClimbRate = 1D;
		this.numInput.Digits = ((uint)(4));
		this.numInput.Numeric = true;
		this.numInput.Value = 1D;
		this.hbox3.Add (this.numInput);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.numInput]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.BorderWidth = ((uint)(7));
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Run");
		this.hbox3.Add (this.button1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button1]));
		w13.Position = 3;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.integerModeCheck = new global::Gtk.CheckButton ();
		this.integerModeCheck.CanFocus = true;
		this.integerModeCheck.Name = "integerModeCheck";
		this.integerModeCheck.Label = global::Mono.Unix.Catalog.GetString ("Round to Nearest Int");
		this.integerModeCheck.DrawIndicator = true;
		this.integerModeCheck.UseUnderline = true;
		this.hbox5.Add (this.integerModeCheck);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.integerModeCheck]));
		w15.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator ();
		this.vseparator3.Name = "vseparator3";
		this.hbox5.Add (this.vseparator3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vseparator3]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.delimiterCheckBox = new global::Gtk.CheckButton ();
		this.delimiterCheckBox.CanFocus = true;
		this.delimiterCheckBox.Name = "delimiterCheckBox";
		this.delimiterCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Custom delimiter");
		this.delimiterCheckBox.DrawIndicator = true;
		this.delimiterCheckBox.UseUnderline = true;
		this.hbox7.Add (this.delimiterCheckBox);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.delimiterCheckBox]));
		w17.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.delimiterEntry = new global::Gtk.Entry ();
		this.delimiterEntry.WidthRequest = 21;
		this.delimiterEntry.Sensitive = false;
		this.delimiterEntry.CanFocus = true;
		this.delimiterEntry.Name = "delimiterEntry";
		this.delimiterEntry.IsEditable = true;
		this.delimiterEntry.MaxLength = 1;
		this.delimiterEntry.InvisibleChar = '●';
		this.hbox7.Add (this.delimiterEntry);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.delimiterEntry]));
		w18.Position = 1;
		this.hbox5.Add (this.hbox7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbox7]));
		w19.Position = 2;
		this.GtkAlignment.Add (this.hbox5);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Advanced Options</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel6;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w22.Position = 5;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Logs</b>");
		this.label4.UseMarkup = true;
		this.vbox1.Add (this.label4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
		w23.Position = 6;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.logWindow = new global::Gtk.TextView ();
		this.logWindow.CanFocus = true;
		this.logWindow.Name = "logWindow";
		this.logWindow.Editable = false;
		this.logWindow.CursorVisible = false;
		this.logWindow.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.logWindow);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w25.Position = 7;
		this.hbox2.Add (this.vbox1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox1]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.hbox4.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator2]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Files</b>");
		this.label3.UseMarkup = true;
		this.vbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.fileList = new global::Gtk.TreeView ();
		this.fileList.CanFocus = true;
		this.fileList.Name = "fileList";
		this.scrolledwindow1.Add (this.fileList);
		this.vbox2.Add (this.scrolledwindow1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow1]));
		w30.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Homogeneous = true;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Add");
		this.hbox6.Add (this.button2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button2]));
		w31.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Remove");
		this.hbox6.Add (this.button3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button3]));
		w32.Position = 1;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		this.hbox4.Add (this.vbox2);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox2]));
		w34.Position = 1;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w35.Position = 0;
		this.hbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
		w36.Position = 1;
		this.Add (this.hbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 708;
		this.DefaultHeight = 404;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.searchButton.Clicked += new global::System.EventHandler (this.SearchForProperty);
		this.button1.Clicked += new global::System.EventHandler (this.CommitChanges);
		this.delimiterCheckBox.Toggled += new global::System.EventHandler (this.delimiterToggled);
		this.button2.Clicked += new global::System.EventHandler (this.AddFile);
		this.button3.Clicked += new global::System.EventHandler (this.RemoveSelected);
	}
}
